language: python
dist: xenial
notifications:
  email:
    recipients:
      - middleware@hexonet.net
    on_success: never
    on_failure: always
python:
  - "3.6"
  - "3.7"
# Trigger a push build on master and dependabot branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^dependabot.*$/
before_install:
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - export TRAVIS_NODE_VERSION="lts/*"
install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
  - source ~/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  - travis_retry pip install --upgrade pip
  - pip -V
  - travis_retry pip install --upgrade -r requirements.txt
  - travis_retry pip install --upgrade -e .
script:
  - "./scripts/pep8check.sh"
  - "./scripts/coverage.sh"
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - nvm install lts/* && nvm use lts/*
        - npm prune
        - npm i
        - npx semantic-release
