Usage Guide
-----------

This part of the documentation, which is mostly prose, begins with some
background information about HEXONET and it's Backend API, then focuses
on step-by-step instructions for getting started with our connector library
hexonet.apiconnector.

.. toctree::
   :maxdepth: 2

   foreword
   installation
   quickstart
   debugging
   config

SDK Documentation
-----------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

Additional Notes
----------------

Design notes, legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 2

   upgrading
   changelog
   contributing
   developmentguide
   license
   contactus
